inicio/urls.py
from django.urls import path
from inicio.views import inicio, registro_cliente, lista_clientes, ver_cliente,eliminar_cliente,editar_cliente


urlpatterns = [
    path('', inicio, name="index"), 
    path('registro/', registro_cliente, name='registro'),  
    path('lista_clientes/', lista_clientes, name='lista'), 
    path('ver-clientes/<int:id>/', ver_cliente,name='ver_clientes'),
    path('eliminar/<int:id>/', eliminar_cliente, name='eliminar_cliente'),
    path('editar_cliente/<int:id>/',editar_cliente,name='editar_cliente'),
    
]

medicamentos/urls.py
from django.urls import path 
from medicamentos import views 

app_name = 'medicamentos'

urlpatterns = [
    path('medicamentos/crear/', views.CrearMedicamento.as_view(), name='crear_medicamento'),
    path('medicamentos/', views.ListadoMedicamentos.as_view(), name='listado_medicamentos'),
    path('medicamentos/<int:pk>/', views.VerMedicamentos.as_view(), name='ver_medicamentos'),
    path('medicamentos/<int:pk>/editar/', views.EditarMedicamentos.as_view(), name='editar_medicamentos'),
    path('medicamentos/<int:pk>/eliminar/', views.EliminarMedicamento.as_view(), name='eliminar_medicamento'),
    path('perfumes/crear/', views.CrearPerfumes.as_view(), name='crear_perfumes'),
    path('perfumes/', views.ListadoPerfumes.as_view(), name='listado_perfumes'),
    path('perfumes/<int:pk>/', views.VerPerfumes.as_view(), name='ver_perfumes'),
    path('perfumes/<int:pk>/editar/', views.EditarPerfumes.as_view(), name='editar_perfumes'),
    path('perfumes/<int:pk>/eliminar/', views.EliminarPerfume.as_view(), name='eliminar_perfume'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inicio.urls')),
    path('medicamentos/',include('medicamentos.urls')),
    path('usuarios/',include('usuarios.urls')),
    ]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import  LogoutView


app_name= 'usuarios'


urlpatterns = [
    path('login/', views.login ,name='login'),
    path('registrarse/', views.registrarse ,name='registrarse'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'),name='logout'),
    path('perfil/editar', views.EditarUsuario, name='editar_perfil'),
    path('perfil/editar/clave', views.CambiarClave.as_view(), name='cambio_clave'),
    path('perfil/', views.perfil, name='perfil'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>
            inicio
        </title>
        {% endblock title_head %}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand">Register System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index'%}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'registro'%}">Registrar</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'lista'%}">Lista de registrados</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_medicamentos'%}">Medicamentos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_perfumes'%}">Perfumes</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "usuarios:editar_perfil" %}>
                            <img src={{request.user.datosextra.avatar.url}} heigth="20px"width="20px" >
                            {{request.user.username}}
                        </a></li>
                        <form action={% url "usuarios:logout" %} method="POST">
                            {% csrf_token %}
                            <input style="border-radius: 10px; background-color: #00bcd4; color: white; border: none; padding: 10px 20px; cursor: pointer;" type="submit" value="Cerrar Sesion">
                        </form>
                        {% else %}
                        <a href="{% url 'usuarios:login' %}" style="border-radius: 10px; background-color: #00bcd4; color: white; padding: 10px 20px; text-decoration: none;">
                            Log In
                        </a>
                        <a href="{% url 'usuarios:registrarse' %}" style="width:105px;margin-left:15px; border-radius: 10px; background-color: #11bcd4; color: white;padding:10px; text-decoration: none;">
                            Registrar Usuario
                        </a>                 
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <header class="masthead">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            {% block h1_header %} 
                            <h1>Bienvenido al sistema de registro de clientes y productos</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block main_base %}
        <main>
            <h2>Bienvenido a nuestro sistema de registro de clientes,en esta pagina podras mantener siempre en orden y guardados los datos mas importantes de tus clientes sin volverte loco,para comenzar a registrar por favor dirigite a las pestaña "Registro" o si queres consultar algun dato de un cliente ya registrado anda a la pestaña "Lista de registrados"</h2>
        </main>
        {% endblock main_base %}
        <footer class="border-top">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

templates/base_lista.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head%}
            Lista
            {% endblock title_head %}
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand">Register System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index'%}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'registro'%}">Registrar</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'lista'%}">Lista de registrados</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_medicamentos'%}">Medicamentos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_perfumes'%}">Perfumes</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "usuarios:editar_perfil" %}>
                            <img src={{request.user.datosextra.avatar.url}} heigth="20px"width="20px" >
                            {{request.user.username}}
                        </a></li>
                        <form action={% url "usuarios:logout" %} method="POST">
                            {% csrf_token %}
                            <input style="border-radius: 10px; background-color: #00bcd4; color: white; border: none; padding: 10px 20px; cursor: pointer;" type="submit" value="Cerrar Sesion">
                        </form>
                        {% else %}
                        <a href="{% url 'usuarios:login' %}" style="border-radius: 10px; background-color: #00bcd4; color: white; padding: 10px 20px; text-decoration: none;">
                            Log In
                        </a>
                        <a href="{% url 'usuarios:registrarse' %}" style="width:105px;margin-left:15px; border-radius: 10px; background-color: #11bcd4; color: white;padding:10px; text-decoration: none;">
                            Registrar Usuario
                        </a>                 
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            {% block descripcion %}
                            <h1>Lista de Registrados</h1>
                            <span class="subheading">Aqui podras buscar a los clientes por sus datos mas importantes.</span>
                            {% endblock descripcion %}
                        </div>
                    </div>
                </div>
            </div>
        </header>          
            {% block main %}
            <main>
            </main>
            {% endblock main %}
        <footer class="border-top">
            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

templates/base_registro.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
            Registro
            {% endblock title_head %}
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand">Register System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index'%}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'registro'%}">Registrar</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'lista'%}">Lista de registrados</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_medicamentos'%}">Medicamentos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_perfumes'%}">Perfumes</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "usuarios:editar_perfil" %}>
                            <img src={{request.user.datosextra.avatar.url}} heigth="20px"width="20px" >
                            {{request.user.username}}
                        </a></li>
                        <form action={% url "usuarios:logout" %} method="POST">
                            {% csrf_token %}
                            <input style="border-radius: 10px; background-color: #00bcd4; color: white; border: none; padding: 10px 20px; cursor: pointer;" type="submit" value="Cerrar Sesion">
                        </form>
                        {% else %}
                        <a href="{% url 'usuarios:login' %}" style="border-radius: 10px; background-color: #00bcd4; color: white; padding: 10px 20px; text-decoration: none;">
                            Log In
                        </a>
                        <a href="{% url 'usuarios:registrarse' %}" style="width:105px;margin-left:15px; border-radius: 10px; background-color: #11bcd4; color: white;padding:10px; text-decoration: none;">
                            Registrar Usuario
                        </a>                 
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            {% block descripcion  %}
                            <h1>Registro de clientes</h1>
                            <span class="subheading">Coloque los datos en las celdas correspondientes</span>
                            {% endblock descripcion  %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        {% block main %}
        <main class="mb-4">
        </main>
        {% endblock main %}
        <!-- Footer-->
        <footer class="border-top">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/base_ver_clientes.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head%}
            Ver clientes
            {% endblock title_head %}
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand">Register System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'index'%}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'registro'%}">Registrar</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'lista'%}">Lista de registrados</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_medicamentos'%}">Medicamentos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'medicamentos:listado_perfumes'%}">Perfumes</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href={% url "usuarios:editar_perfil" %}>
                            <img src={{request.user.datosextra.avatar.url}} heigth="20px"width="20px" >
                            {{request.user.username}}
                        </a></li>
                        <form action={% url "usuarios:logout" %} method="POST">
                            {% csrf_token %}
                            <input style="border-radius: 10px; background-color: #00bcd4; color: white; border: none; padding: 10px 20px; cursor: pointer;" type="submit" value="Cerrar Sesion">
                        </form>
                        {% else %}
                        <a href="{% url 'usuarios:login' %}" style="border-radius: 10px; background-color: #00bcd4; color: white; padding: 10px 20px; text-decoration: none;">
                            Log In
                        </a>
                        <a href="{% url 'usuarios:registrarse' %}" style="width:105px;margin-left:15px; border-radius: 10px; background-color: #11bcd4; color: white;padding:10px; text-decoration: none;">
                            Registrar Usuario
                        </a>                 
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            {%block descripcion%}
                            <h1>Datos Detallados</h1>
                            <span class="subheading">En esta seccion se encuentras los datos detallados de los clientes registraods</span>
                            {%endblock descripcion%}
                        </div>
                    </div>
                </div>
            </div>
        </header>          
            {% block main %}
            <main>
            </main>
            {% endblock main %}
        <footer class="border-top">
            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>