inicio/urls.py
from django.urls import path
from inicio.views import inicio, registro_cliente, lista_clientes, ver_cliente,eliminar_cliente,editar_cliente


urlpatterns = [
    path('', inicio, name="index"), 
    path('registro/', registro_cliente, name='registro'),  
    path('lista_clientes/', lista_clientes, name='lista'), 
    path('ver-clientes/<int:id>/', ver_cliente,name='ver_clientes'),
    path('eliminar/<int:id>/', eliminar_cliente, name='eliminar_cliente'),
    path('editar_cliente/<int:id>/',editar_cliente,name='editar_cliente'),
    
]

medicamentos/urls.py
from django.urls import path 
from medicamentos import views 

app_name = 'medicamentos'

urlpatterns = [
    path('medicamentos/crear/', views.CrearMedicamento.as_view(), name='crear_medicamento'),
    path('medicamentos/', views.ListadoMedicamentos.as_view(), name='listado_medicamentos'),
    path('medicamentos/<int:pk>/', views.VerMedicamentos.as_view(), name='ver_medicamentos'),
    path('medicamentos/<int:pk>/editar/', views.EditarMedicamentos.as_view(), name='editar_medicamentos'),
    path('medicamentos/<int:pk>/eliminar/', views.EliminarMedicamento.as_view(), name='eliminar_medicamento'),
    path('perfumes/crear/', views.CrearPerfumes.as_view(), name='crear_perfumes'),
    path('perfumes/', views.ListadoPerfumes.as_view(), name='listado_perfumes'),
    path('perfumes/<int:pk>/', views.VerPerfumes.as_view(), name='ver_perfumes'),
    path('perfumes/<int:pk>/editar/', views.EditarPerfumes.as_view(), name='editar_perfumes'),
    path('perfumes/<int:pk>/eliminar/', views.EliminarPerfume.as_view(), name='eliminar_perfume'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inicio.urls')),
    path('medicamentos/',include('medicamentos.urls')),
    path('usuarios/',include('usuarios.urls')),
    ]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

medicamentos/models.py
from django.db import models

class Medicamentos(models.Model):
    marca = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=50)
    precio = models.CharField(max_length=10)
    def __str__(self):
        return f'|Marca: {self.marca}| |Descripcion: {self.descripcion}| |Precio: ${self.precio} por caja'
    
class Perfumes(models.Model):
    marca = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=50)
    genero = models.CharField(max_length=10,default = 'Unisex')
    precio = models.CharField(max_length=10)
    def __str__(self):
        return f'|Marca: {self.marca}| |Descripcion: {self.descripcion}| Genero: {self.genero} |Precio: ${self.precio} por unidad.'

medicamentos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from medicamentos.models import Medicamentos, Perfumes
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



class CrearMedicamento(LoginRequiredMixin,CreateView):
    model = Medicamentos
    template_name = "medicamentos/crear_medicamento.html"
    success_url = reverse_lazy('medicamentos:listado_medicamentos')
    fields = ['marca', 'descripcion', 'precio']


class ListadoMedicamentos(LoginRequiredMixin,ListView):
    model = Medicamentos
    template_name = "medicamentos/lista_medicamentos.html"
    context_object_name = 'medicamentos'
    

class VerMedicamentos(LoginRequiredMixin,DetailView):
    model = Medicamentos
    template_name = "medicamentos/ver_medicamentos.html"


class EditarMedicamentos(LoginRequiredMixin,UpdateView):
    model = Medicamentos
    template_name = "medicamentos/editar_medicamentos.html"
    success_url = reverse_lazy('medicamentos:listado_medicamentos')
    fields = ['marca', 'descripcion', 'precio']



class EliminarMedicamento(LoginRequiredMixin,DeleteView):
    model = Medicamentos
    template_name = "medicamentos/eliminar_medicamento.html"
    success_url = reverse_lazy('medicamentos:listado_medicamentos')




class CrearPerfumes(LoginRequiredMixin,CreateView):
    model = Perfumes
    template_name = "medicamentos/crear_perfumes.html"  
    success_url = reverse_lazy('medicamentos:listado_perfumes')  
    fields = ['marca', 'descripcion','genero', 'precio']


class ListadoPerfumes(LoginRequiredMixin,ListView):
    model = Perfumes
    template_name = "medicamentos/lista_perfumes.html"  
    context_object_name = 'perfumes'  

class VerPerfumes(LoginRequiredMixin,DetailView):
    model = Perfumes
    template_name = "medicamentos/ver_perfumes.html"
    
    
class EditarPerfumes(LoginRequiredMixin,UpdateView):
    model = Perfumes
    template_name = "medicamentos/editar_perfumes.html"
    success_url = reverse_lazy('medicamentos:listado_perfumes')
    fields = ['marca', 'descripcion','genero', 'precio']


class EliminarPerfume(LoginRequiredMixin,DeleteView):
    model = Perfumes
    template_name = "medicamentos/eliminar_perfume.html"
    success_url = reverse_lazy('medicamentos:listado_perfumes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['perfume'] = self.get_object() 
        return context

medicamentos/templates/medicamentos/crear_medicamento.html
{% extends "base_registro.html" %}

{% block title_head %}
Registrar Medicamento
{% endblock title_head %}

{% block descripcion %}
<h1>Registro de Medicamentos</h1>
<span class="subheading">Seccion dedicada al registro de medicamentos para nuestra base de datos.</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Registrar Medicamento/Crema</h1>
    <form action="{% url 'medicamentos:crear_medicamento' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>

</main>
{% endblock main %}

medicamentos/templates/medicamentos/crear_perfumes.html
{% extends "base_registro.html" %}

{% block title_head %}
Registrar Medicamento
{% endblock title_head %}

{% block descripcion %}
<h1>Registro de Perfumes</h1>
<span class="subheading">Seccion dedicada al registro de perfumes para nuestra base de datos.</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Registrar perfume</h1>
    <form action="{% url 'medicamentos:crear_perfumes' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>

</main>
{% endblock main %}

medicamentos/templates/medicamentos/editar_medicamentos.html
{% extends "base_registro.html" %}

{% block title_head %}
Editar Medicamento
{% endblock title_head %}

{% block descripcion %}
<h1>Editor de datos (Medicamentos)</h1>
<span class="subheading">Editor de datos de los medicamentos registrados.</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Editar Medicamento/Crema</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

</main>
{% endblock main %}

medicamentos/templates/medicamentos/editar_perfumes.html
{% extends "base_registro.html" %}

{% block title_head %}
Editar Perfumes
{% endblock title_head %}

{% block descripcion %}
<h1>Edicion de datos (Perfumes)</h1>
<span class="subheading">Editor de datos de los perfumes registrados.</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Registrar perfume</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

</main>
{% endblock main %}

medicamentos/templates/medicamentos/eliminar_medicamento.html
{% extends "base_registro.html" %}

{% block title_head %}
Eliminar Medicamento
{% endblock title_head %}

{% block descripcion %}
<h1>Eliminar Medicamento de la base de datos.</h1>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Eliminar Medicamento</h1>
    <form method="POST" action="{% url 'medicamentos:eliminar_medicamento' object.id %}">
        {% csrf_token %}
        <p>¿Estás seguro que deseas eliminar el medicamento "{{ object }}"?</p>
        <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'medicamentos:listado_medicamentos' %}">Cancelar</a>
</main>
{% endblock main %}

medicamentos/templates/medicamentos/eliminar_perfume.html
{% extends "base_registro.html" %}

{% block title_head %}
Eliminar Perfume
{% endblock title_head %}

{% block descripcion %}
<h1>Eliminar perfume de la base de datos.</h1>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Eliminar perfume</h1>
    <form action="{% url 'medicamentos:eliminar_perfume' perfume.id %}" method="POST">
        {% csrf_token %}
        <p>¿Realmente desea eliminar el perfume "{{ perfume }}"?</p>
        <button type="submit">Eliminar</button>
    </form>
</main>
{% endblock main %}

medicamentos/templates/medicamentos/lista_medicamentos.html
{% extends "base_lista.html" %}

{% block title_head %}
    Listado Medicamentos
{% endblock title_head %}
{% block descripcion %}
<h1>Lista de medicamentos</h1>
<span class="subheading">Lista de medicamentos registrados , con su descripcion y precio (por caja).</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Listado Medicamentos</h1>
    <ul>
        {% for medicamento in medicamentos %}
            <li>{{medicamento}}
                <a href="{% url 'medicamentos:ver_medicamentos' medicamento.id %}">-Ver Detallado-</a><br>
                <a href="{% url 'medicamentos:editar_medicamentos' medicamento.pk %}">-Editar-</a>
                <a href="{% url 'medicamentos:eliminar_medicamento' medicamento.pk %}">-Eliminar-</a>
            </li>
        {% empty %}
            <p>No se encontraron medicamentos con ese nombre.</p>
        {% endfor %}
    </ul>
    <a href="{% url 'medicamentos:crear_medicamento' %}">Registrar Medicamento</a>
{% endblock main %}

medicamentos/templates/medicamentos/lista_perfumes.html
{% extends "base_lista.html" %}

{% block title_head %}
    Listado Medicamentos
{% endblock title_head %}
{% block descripcion %}
<h1>Lista de perfumes</h1>
<span class="subheading">Lista de perfumes registrados , con su descripcion y precio (por unidad).</span>
{% endblock descripcion %}

{% block main %}
<main>
    <h1>Listado perfumeria</h1>
    <ul>
        {% for perfume in perfumes %}
            <li>{{perfume}}
                <li>
                    <a href={% url "medicamentos:ver_perfumes" perfume.id %}>-Ver Detallado-</a><br>
                </li>
                <li>
                    <a href={% url "medicamentos:editar_perfumes" perfume.id %}>-Editar-</a><br>
                </li>
                <li>
                    <a href={% url "medicamentos:eliminar_perfume" perfume.id %}>-Eliminar-</a><br>
                </li>
            </li>
        {% empty %}
            <p>No se encontraron perfumes con ese nombre.</p>
        {% endfor %}
    </ul>
    <a href="{% url 'medicamentos:crear_perfumes' %}">Registrar Perfume</a>
{% endblock main %}

medicamentos/templates/medicamentos/ver_medicamentos.html
{% extends "base_ver_clientes.html" %}

{% block title_head %}
    ver medicamentos
{% endblock title_head %}
{%block descripcion%}
<h1>Medicamentos Detallados</h1>
<span class="subheading">En esta seccion se encuentras los datos detallados de los medicamentos registrados</span>
{%endblock descripcion%}
{% block main %}
<ul>
    <li>Marca: {{medicamentos.marca}}</li>
    <li>Descripcion: {{medicamentos.descripcion}}</li>
    <li>Precio: ${{medicamentos.precio}}</li>
</ul>
{% endblock main %}

medicamentos/templates/medicamentos/ver_perfumes.html
{% extends "base_ver_clientes.html" %}

{% block title_head %}
    ver perfumes
{% endblock title_head %}
{%block descripcion%}
<h1>Perfumes Detallados</h1>
<span class="subheading">En esta seccion se encuentras los datos detallados de los perfumes registrados</span>
{%endblock descripcion%}
{% block main %}
<ul>
    <li>Marca: {{perfumes.marca}}</li>
    <li>Descripcion: {{perfumes.descripcion}}</li>
    <li>Genero: {{perfumes.genero}}</li>
    <li>Precio: ${{perfumes.precio}}</li>
</ul>
{% endblock main %}